#!/usr/bin/env bash

$HOME/.config/bspwm/scripts/_autostart.sh

bspc config border_width 2
bspc config window_gap 10
bspc config split_ratio 0.50
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc rule -a Alacritty desktop="^1" follow=on focus=on
bspc rule -a firefox desktop="^2" follow=on focus=on
