;==========================================================
;
;
;   ██████╗  ██████╗ ██╗  ██╗   ██╗██████╗  █████╗ ██████╗
;   ██╔══██╗██╔═══██╗██║  ╚██╗ ██╔╝██╔══██╗██╔══██╗██╔══██╗
;   ██████╔╝██║   ██║██║   ╚████╔╝ ██████╔╝███████║██████╔╝
;   ██╔═══╝ ██║   ██║██║    ╚██╔╝  ██╔══██╗██╔══██║██╔══██╗
;   ██║     ╚██████╔╝███████╗██║   ██████╔╝██║  ██║██║  ██║
;   ╚═╝      ╚═════╝ ╚══════╝╚═╝   ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝
;
;
;   To learn more about how to configure Polybar
;   go to https://github.com/polybar/polybar
;
;   The README contains a lot of information
;
;==========================================================

[global/wm]
include-file = "$HOME/.config/polybar/themes/catppuccin-mocha.ini"

[bar/main]
width = 98.5%
height = 24pt
offset-x=0.8%
offset-y=10px
dpi = 96
background = ${colors.base}
foreground = ${colors.text}
border-size = 0
padding-left = 0
padding-right = 2
module-margin = 1
font-0 = Iosevka Nerd Font;2
modules-left = menu bspwm
modules-center = time
modules-right = github volume wifi wlan battery power
cursor-click = pointer
cursor-scroll = ns-resize
enable-ipc = true

[settings]
screenchange-reload = true

[module/bspwm]
type = internal/xworkspaces
label-active = 󰮯
label-active-foreground = ${colors.peach}
label-active-padding = 1
label-occupied = 󰊠
label-occupied-padding = 1
label-occupied-foreground = ${colors.sky}
label-urgent = 󰊠
label-urgent-background = ${colors.red}
label-urgent-padding = 1
label-empty = 
label-empty-foreground = ${colors.overlay0}
label-empty-padding = 1

[module/menu]
type = custom/text
content = 
content-foreground = ${colors.blue}
content-padding = 1
click-left = rofi -show drun

[module/time]
type = internal/date
label = %time%
time = %H:%M

[module/volume]
type = internal/pulseaudio
format-volume = <ramp-volume>  <label-volume>
format-muted = <label-muted>
label-volume = %percentage%%
label-muted = 
ramp-volume-0 = 
ramp-volume-1 = 
ramp-volume-2 = 

[module/wifi]
type = internal/network
interface = wlp3s0
interface-type = wireless
accumulate-stats = true
format-connected = <ramp-signal>
format-disconnected = 󰤮
format-packetloss = <animation-packetloss>
ramp-signal-0 = 󰤫
ramp-signal-1 = 󰤯
ramp-signal-2 = 󰤟
ramp-signal-3 = 󰤢
ramp-signal-4 = 󰤥
ramp-signal-5 = 󰤨
animation-packetloss-0 = 󰤫
animation-packetloss-1 = 󰤩
animation-packetloss-framerate = 300

[module/wlan]
type = internal/network
interface = enp0s25
interface-type = wired
label-connected = 
label-disconnected = 󰈀

[module/battery]
type = internal/battery
battery = BAT0
adapter = AC
time-format = %H:%M
format-charging = <animation-charging>  <label-charging>
format-discharging = <ramp-capacity>  <label-discharging>
format-full = <ramp-capacity>  <label-full>
format-low = <label-low>  <animation-low>
label-charging = %percentage%%
label-discharging = %percentage%%
label-full = %percentage%%
label-low = %percentage%%
ramp-capacity-0 = 
ramp-capacity-1 = 
ramp-capacity-2 = 
ramp-capacity-3 = 
ramp-capacity-4 = 
bar-capacity-width = 10
animation-charging-0 = 
animation-charging-1 = 
animation-charging-2 = 
animation-charging-3 = 
animation-charging-4 = 
animation-charging-framerate = 300
animation-discharging-0 = 
animation-discharging-1 = 
animation-discharging-2 = 
animation-discharging-3 = 
animation-discharging-4 = 
animation-discharging-framerate = 300
animation-low-0 = !
animation-low-1 = 
animation-low-framerate = 300

[module/github]
type = internal/github
token = ${env:GITHUB_ACCESS_TOKEN}
user = aldiipratama
empty-notifications = false
interval = 10
format =   <label>
label = %notifications%
format-offline = <label-offline>
label-offline = Offline

[module/power]
type = custom/text
content = ⏻
content-foreground = ${colors.red}
content-padding = 1
click-left = rofi -show drun
